import { AlertTriangle, Info } from 'lucide-react'
import type { NetworkBehaviorProfile } from '../../types'
import { levelTextColor } from '../../utils/levelColors'

interface Props {
  profile: NetworkBehaviorProfile
  personId: string
}

interface FlagEntry {
  level: string
  title: string
  detail: string
}

function buildFlags(profile: NetworkBehaviorProfile): FlagEntry[] {
  const flags: FlagEntry[] = []

  const bp = profile.brokerage_position
  if (bp.level === 'HIGH' || bp.level === 'MEDIUM') {
    flags.push({
      level: bp.level,
      title: `${bp.level} BROKERAGE POSITION`,
      detail: `This entity occupies a strategic bridging role in the network (score: ${(bp.score * 100).toFixed(1)}%). ${bp.explanation}`,
    })
  }

  const coord = profile.coordination_indicators
  if (coord.level === 'HIGH' || coord.level === 'MEDIUM') {
    flags.push({
      level: coord.level,
      title: `${coord.level} COORDINATION INDICATOR`,
      detail: `Strong coordination patterns detected. Score: ${(coord.score * 100).toFixed(1)}%. Degree centrality: ${coord.degree_centrality.toFixed(4)}, Interaction strength: ${coord.normalized_interaction_strength.toFixed(4)}.`,
    })
  }

  const anomaly = profile.activity_anomaly
  if (anomaly.level === 'HIGH' || anomaly.level === 'MEDIUM') {
    flags.push({
      level: anomaly.level,
      title: `${anomaly.level} ACTIVITY ANOMALY`,
      detail: anomaly.explanation,
    })
  }

  const cc = profile.cross_case_significance
  if (cc.level === 'HIGH' || cc.level === 'MEDIUM') {
    flags.push({
      level: cc.level,
      title: `${cc.level} CROSS-CASE SIGNIFICANCE`,
      detail: `This entity appears across ${cc.distinct_case_count} distinct investigation case(s). Cross-case score: ${(cc.score * 100).toFixed(1)}%.`,
    })
  }

  return flags
}

export default function FlagExplanation({ profile, personId }: Props) {
  const flags = buildFlags(profile)

  return (
    <div className="bg-bg-card border border-border rounded-lg p-5">
      {/* Header */}
      <div className="flex items-center gap-2.5 mb-4">
        <div className="w-8 h-8 rounded-lg bg-yellow-500/10 border border-yellow-500/20
                        flex items-center justify-center flex-shrink-0">
          <AlertTriangle size={15} className="text-yellow-400" />
        </div>
        <div>
          <h3 className="text-xs font-semibold text-gray-300 tracking-widest uppercase">
            Why Was This Entity Flagged?
          </h3>
          <p className="text-[10px] text-gray-600 mt-0.5">
            Analytical observations for entity {personId}
          </p>
        </div>
      </div>

      {/* Flags */}
      {flags.length > 0 ? (
        <div className="space-y-3">
          {flags.map((flag, i) => (
            <div
              key={i}
              className={`rounded-lg border p-3.5 ${
                flag.level === 'HIGH'
                  ? 'bg-red-500/5 border-red-500/20'
                  : 'bg-amber-500/5 border-amber-500/20'
              }`}
            >
              <div className="flex items-center gap-2 mb-1.5">
                <AlertTriangle
                  size={12}
                  className={flag.level === 'HIGH' ? 'text-red-400' : 'text-amber-400'}
                />
                <span className={`text-xs font-semibold tracking-wide ${levelTextColor(flag.level)}`}>
                  {flag.title}
                </span>
              </div>
              <p className="text-[12px] text-gray-400 leading-relaxed">{flag.detail}</p>
            </div>
          ))}
        </div>
      ) : (
        <div className="flex items-center gap-2.5 py-3 px-4 bg-green-500/5 border border-green-500/20 rounded-lg">
          <Info size={14} className="text-green-400 flex-shrink-0" />
          <p className="text-xs text-green-400">
            No significant analytical indicators detected for this entity.
          </p>
        </div>
      )}

      {/* Disclaimer */}
      <div className="mt-4 pt-3 border-t border-border">
        <p className="text-[10px] text-gray-600 leading-relaxed">
          <span className="text-gray-500 font-semibold">⚠ Analytical Notice: </span>
          The above indicators are generated by automated network analysis and represent
          analytical observations only. They do not constitute evidence of wrongdoing,
          accusations of criminal activity, or legal conclusions. All findings require
          further human review and investigation before any action is taken.
        </p>
      </div>
    </div>
  )
}
